### ISSUE TITLE
2 ошибки 

### ISSUE THREAD

**Issue by kinlok951** [semyon492/vii#12]
далуется на Parse error: syntax error, unexpected token "=", expecting ";" in system\data\db.php on line 13
и на system\init.php on line 87 мол нету функции super_query();

**Comment by semyon492** [comment]
Ошибка в install.php

**Comment by kinlok951** [comment]
при установке сразу выбевает ткаое может и в installe.php

**Comment by semyon492** [comment]
Исправленно
