### ISSUE TITLE
оштбка в install.php

### ISSUE THREAD

**Issue by kinlok951** [semyon492/vii#14]
Fatal error: Uncaught Error: Call to a member function query() on null in D:\OpenServer\domains\test.com\install.php:481 Stack trace: #0 {main} thrown in D:\OpenServer\domains\test.com\install.php on line 481

**Comment by kinlok951** [comment]
Fatal error: Uncaught Error: Call to a member function query() on null in D:\OpenServer\domains\test.com\install.php:609 Stack trace: #0 {main} thrown in D:\OpenServer\domains\test.com\install.php on line 609

**Comment by semyon492** [comment]
[Исправление](https://github.com/semyon492/vii/issues/12)
