### ISSUE TITLE
фигня какаето происходит 

### ISSUE THREAD

**Issue by kinlok951** [semyon492/vii#22]
Warning: Undefined variable $spBar in D:\OpenServer\domains\friendes.com\system\functions.php on line 1548
{"title":"\u0421\u043e\u0446\u0438\u0430\u043b\u044c\u043d\u0430\u044f \u0441\u0435\u0442\u044c","user_pm_num":"","new_news":"","new_ubm":"","gifts_link":"\/balance","support":"","news_link":"","demands":"","new_photos":"","new_photos_link":"1","requests_link":"","new_groups":"","new_groups_lnk":"\/groups","sbar":"","content":"

и в шаблоне где .tpl вечная загрузка уже налоела

**Comment by semyon492** [comment]
Добавь строку

`$spBar = $spBar ?? null;`
